<rogram> ::= <statement>

<statement> ::= <ass_statement>
  | <while_statement>
  | <if_statement>
  | "print(" <expression> ")"
  | <statement> ";" <statement>

<ass_statement> ::= <variable> ":=" <expression>

<while_statement> ::= "while(" <relationalEXPRESSION> "){" <statement> "}"

<if_statement> ::= "if(" <relationalEXPRESSION> "){" <statement> "}"
  | "if(" <relationalEXPRESSION> "){" <statement> "}"
    "else {" <statement> "}"
 
 
<expression> ::= <relationalEXPRESSION> | <arithmeticEXPRESSION>

<arithmeticEXPRESSION> ::= <number>
  | "(" <arithmeticEXPRESSION> ")"
  | <arithmeticEXPRESSION> <arithmeticOPERATOR> <arithmeticEXPRESSION>
  | <variable>

<number> ::= [0-9]+

<arithmeticOPERATOR> ::= "+" | "-" | "*" | "/"

<variable> ::= [a-z]+

<relationalEXPRESSION> ::= <bool>
  | "(" <relationalEXPRESSION> ")"
  | "!" <relationalEXPRESSION>
  | <relationalEXPRESSION> <logicalOPERATOR> <relationalEXPRESSION>
  | <variable>
  | <arithmeticEXPRESSION> <equalOrnotequal> <arithmeticEXPRESSION>
  | <relationalEXPRESSION> <equalOrnotequal> <relationalEXPRESSION>
  | <arithmeticEXPRESSION> <relationalOPERATOR> <arithmeticEXPRESSION>

<logicalOPERATOR> ::= "and" | "or" | "not"

<bool> ::= "true" | "false"

<equalOrnotequal> ::= "==" | "!="

<relationalOPERATOR> ::= ">" | ">=" | "<" | "<="